<html>
<head>
<title>测试模板</title>
</head>
<body>
<ul>
<!--{volist name="fruits" id="it" offset="3"}-->
	<!--{if condition="$it.type == 0"}-->
		<!--{if condition="$it.num > 0"}-->
			<li>{{$it.name}}</li>
		<!--{/if}-->
    <!--{elseif condition="$it.type == 1"/}-->
    	<li>{{$it.name}}</li>
    <!--{else/}-->
    	<li>{{$it.name}}</li>
    <!--{/if}-->
<!--{/volist}-->
<ul>
<ul>
<!--{foreach name="fruits" key="k", item="vo"}-->
	<li>{{$k}}|{{$vo}}</li>
<!--{/foreach}-->
</ul>
</body>
</html>