<html>
<head>
<title>测试模板</title>
</head>
<body>
<ul>
<!--{volist name="fruits" id="it" offset="3"}-->
	<!--{if condition="$it.type.no == 0"}-->
		<!--{if condition="$it.num > 0"}-->
			<li>{{$it.name}}</li>
		<!--{/if}-->
    <!--{elseif condition="$it.type.no == 1"/}-->
    	<li>{{$it.name}}</li>
    <!--{else/}-->
    	<li>{{$it.name}}</li>
    <!--{/if}-->
<!--{/volist}-->
<ul>
<ul>
<!--{foreach name="fruits" key="k", item="vo"}-->
	<li>{{$k}}|{{$vo}}</li>
<!--{/foreach}-->
</ul>
<!--{for start="10" end="50" name="j" step="2"}-->
	{{$j}}
<!--{/for}-->
<!--{for start="10" end="50" name="j" step="2"}-->
	{{$j}}
<!--{/for}-->
<!--{for start="10" end="50" name="i" step="2"}-->
	<!--{for start="10" end="50" name="j" step="2"}-->
		{{$i}}-{{$j}}
	<!--{/for}-->
<!--{/for}-->
</body>
</html>